package com.quasar.paul.computerbasics;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.widget.ImageView;
import android.widget.TextView;

public class HardwareScrollingActivity extends AppCompatActivity {

    String[] HardwareList = {
            "AGP: Accelerated Graphics Port",
            "APM: Advanced Power Management",
            "BIOS: Basic Input Output System",
            "Bus",
            "CD-R",
            "CD-ROM",
            "CD-RW",
            "COM port",
            "CPU",
            "DVD",
            "Floppy Drive",
            "Hard Drive",
            "Heat Sink",
            "Joystick",
            "Keyboard",
            "LCD",
            "Memory",
            "Microphone",
            "Modem",
            "Monitor",
            "Mother Board",
            "Mouse",
            "Network Card",
            "Parallel Port",
            "PSU: Power Supply Unit",
            "Printer",
            "Processor",
            "PS/2",
            "RAID: Redundant Array of Inexpensive Disks",
            "RAM: Read Only Memory",
            "Riser Board",
            "SCSI: Small Computer System Interface",
            "Serial Port",
            "Sound Card",
            "Speakers",
            "SPS: Standby Power Supply",
            "Surge Suppressor",
            "UPS: Uninterruptible Power Supply",
            "Video Card",
            "Zip Drive"
    };

    String[] HardwareDetails = {
            "The Accelerated Graphics Port (often shortened to AGP) is a high-speed point-to-point channel for attaching " +
                    "a video card to a computer system, primarily to assist in the acceleration of 3D computer graphics." +
                    " It was originally designed as a successor to PCI-type connections for video cards. Since 2004, AGP " +
                    "has been progressively phased out in favor of PCI Express (PCIe); by mid-2008, PCI Express cards dominated" +
                    " the market and only a few AGP models were available.",
            "Advanced power management (APM) is an API developed by Intel and Microsoft and released in 1992[1] which enables " +
                    "an operating system running an IBM-compatible personal computer to work with the BIOS (part of the computer's" +
                    " firmware) to achieve power management. \n\n Revision 1.2 was the last version of the APM specification," +
                    "released in 1997. ACPI is intended as the successor to APM. Microsoft dropped support" +
                    "for APM in Windows Vista. The Linux Kernel still mostly supports APM, with the last" +
                    "fully functional APM support shipping in 3.3.",
            "The BIOS is a type of firmware used to perform hardware initialization during the booting " +
                    "process (power-on startup) on IBM PC compatible computers, and to provide runtime" +
                    "services for operating systems and programs. The BIOS firmware is bult into personal" +
                    "computers, and it is the first software they run when powered on. The name itself originates" +
                    "from the Basic Input/Ouput System used in the CP/M operating system in 1975. Originally" +
                    "proprietary to the IBM PC, the BIOS has been reverse engineered by companies looking to " +
                    "create compatible systems and the interface of that original system serves as a de facto" +
                    "standard.\n\nThe fundamental purposes of the BIOS in modern PCs are to initialize and test" +
                    "the system hardware components, and to load a boot loader or an operating system from a " +
                    "mass memory device. The BIOS additionally provided an abstraction layer for the hardware, i.e.," +
                    "a consistent way for application programs and operating systems to interact with the keyboard" +
                    ", display, and other input/output (I/O) devices.",
            "In computer architecture, a bus or buss is communication system that transfers data between components" +
                    " inside computer, or between computers. This expression covers all related hardware components" +
                    " (wire, optical fiber, etc.) and software, including communication protocols.\n\nModern computer" +
                    " buses can use both parallel and bit serial connections, and can be wired in either a multidrop" +
                    " (electrical parallel) or daisy chain topology or connected by switched hubs, as in the case of " +
                    "USB.",
            "CD-R (Compact Disc-Recordable) is a digital optical disc storage format. A CD-R disc is a compact disc that" +
                    " can be written once and read arbitrarily many times.",
            "A CD-ROM is a pre-pressed optical compact disc which contains data. The name is a acronym which stands for" +
                    " \"Compact Disc Read-Only Memory\". Computer can read CD-ROMs, btu cannot write to CD-ROMs which are" +
                    " not writable or erasable.",
            "CD-RW (Compact Disc-ReWritable) is a digital optical disc storage format. A CD-RW disc is a compact disc that" +
                    " can be written, read arbitrarily many times, erased, and written again. The technology was introduced" +
                    " in 1997.",
            "CoM (Communication port) is the original, yet still common, name of the serial port interface on IBM PC-compatible" +
                    " computers. It might refer not only to physical ports, but also to virtual ports, such as ports created by" +
                    " Bluetooth or USB-to-serial adapters.",
            "A central processing unit (CPU) is the electronic circuitry within a computer that carries out the instructions of a computer program by performing the basic arithmetic, logical, control and input/output (I/O) operations specified by the instructions. The term has been used in the computer industry at least since the early 1960s. Traditionally, the term \"CPU\" refers to a processor, more specifically to its processing unit and control unit (CU), distinguishing these core elements of a computer from external components such as main memory and I/O circuitry.\n" +
                    "The form, design and implementation of CPUs have changed over the course of their history, but their fundamental operation remains almost unchanged. Principal components of a CPU include the arithmetic logic unit (ALU) that performs arithmetic and logic operations, processor registers that supply operands to the ALU and store the results of ALU operations, and a control unit that fetches instructions from memory and \"executes\" them by directing the coordinated operations of the ALU, registers and other components.\n" +
                    "Most modern CPUs are microprocessors, meaning they are contained on a single integrated circuit (IC) chip. An IC that contains a CPU may also contain memory, peripheral interfaces, and other components of a computer; such integrated devices are variously called microcontrollers or systems on a chip (SoC). Some computers employ a multi-core processor, which is a single chip containing two or more CPUs called \"cores\"; in that context, single chips are sometimes referred to as \"sockets\". Array processors or vector processors have multiple processors that operate in parallel, with no unit considered central.",
            "DVD (\"digital versatile disc\" or \"digital video disc\") is a digital optical disc storage format invented and co-developed by Philips, Sony, Toshiba, and Panasonic in 1995. The medium can store any kind of digital data and is widely used for software and other computer files as well as video programs watched using DVD players. DVDs offer higher storage capacity than compact discs while having the same dimensions.\n" +
                    "Pre-recorded DVDs are mass-produced using molding machines that physically stamp data onto the DVD. Such discs are a form of DVD-ROMs, because data can only be read and not written or erased. Blank recordable DVD discs (DVD-R and DVD+R) can be recorded once using a DVD recorder and then function as a DVD-ROM. Rewritable DVDs (DVD-RW, DVD+RW, and DVD-RAM) can be recorded and erased many times.\n" +
                    "DVDs are used in DVD-Video consumer digital video format and in DVD-Audio consumer digital audio format as well as for authoring DVD discs written in a special AVCHD format to hold high definition material (often in conjunction with AVCHD format camcorders). DVDs containing other types of information may be referred to as DVD data discs.",
            "A floppy disk, also called a floppy, diskette or just disk, is a type of disk storage composed of a disk of thin and flexible magnetic storage medium, sealed in a rectangular plastic carrier lined with fabric that removes dust particles. Floppy disks are read and written by a floppy disk drive (FDD).\n" +
                    "Floppy disks, initially as 8-inch (200 mm) media and later in 5¼-inch (133 mm) and 3½-inch (90 mm) sizes, were a ubiquitous form of data storage and exchange from the mid-1970s into the late 2000s.By 2007, computers were rarely manufactured with installed floppy disk drives; 3½-inch floppy disks can be used with an external USB floppy disk drive, but USB drives for 5¼-inch, 8-inch, and non-standard diskettes are rare to non-existent. These formats are usually handled by older equipment.\n" +
                    "While floppy disk drives still have some limited uses, especially with legacy industrial computer equipment, they have been superseded by data storage methods with much greater capacity, such as USB flash sticks, flash storage cards, portable external hard disk drives, optical discs, and storage available through computer networks.",
            "A hard disk drive (HDD), hard disk, hard drive or fixed disk is a data storage device used for storing and retrieving digital information using one or more rigid rapidly rotating disks (platters) coated with magnetic material. The platters are paired with magnetic heads arranged on a moving actuator arm, which read and write data to the platter surfaces. Data is accessed in a random-access manner, meaning that individual blocks of data can be stored or retrieved in any order and not only sequentially. HDDs are a type of non-volatile memory, retaining stored data even when powered off.\n" +
                    "Introduced by IBM in 1956, HDDs became the dominant secondary storage device for general-purpose computers by the early 1960s. Continuously improved, HDDs have maintained this position into the modern era of servers and personal computers. More than 200 companies have produced HDDs historically, though after extensive industry consolidation most current units are manufactured by Seagate, Toshiba and Western Digital. As of 2016, HDD production (exabytes per year) is growing, although unit shipments and sales revenues are declining. The primary competing technology for secondary storage is flash memory in the form of solid-state drives (SSDs), which have higher data transfer rates, higher areal storage density, better reliability, and much lower latency and access times. While SSDs have higher cost per bit, SSDs are replacing HDDs where speed, power consumption, small size, and durability are important.The primary characteristics of an HDD are its capacity and performance. Capacity is specified in unit prefixes corresponding to powers of 1000: a 1-terabyte (TB) drive has a capacity of 1,000 gigabytes (GB; where 1 gigabyte = 1 billion bytes). Typically, some of an HDD's capacity is unavailable to the user because it is used by the file system and the computer operating system, and possibly inbuilt redundancy for error correction and recovery. Performance is specified by the time required to move the heads to a track or cylinder (average access time) plus the time it takes for the desired sector to move under the head (average latency, which is a function of the physical rotational speed in revolutions per minute), and finally the speed at which the data is transmitted (data rate).\n" +
                    "The two most common form factors for modern HDDs are 3.5-inch, for desktop computers, and 2.5-inch, primarily for laptops. HDDs are connected to systems by standard interface cables such as PATA (Parallel ATA), SATA (Serial ATA), USB or SAS (Serial attached SCSI) cables.",
            "A heat sink (also commonly spelled heatsink) is a passive heat exchanger that transfers the heat generated by an electronic or a mechanical device to a fluid medium, often air or a liquid coolant, where it is dissipated away from the device, thereby allowing regulation of the device's temperature at optimal levels. In computers, heat sinks are used to cool central processing units or graphics processors. Heat sinks are used with high-power semiconductor devices such as power transistors and optoelectronics such as lasers and light emitting diodes (LEDs), where the heat dissipation ability of the component itself is insufficient to moderate its temperature.\n" +
                    "A heat sink is designed to maximize its surface area in contact with the cooling medium surrounding it, such as the air. Air velocity, choice of material, protrusion design and surface treatment are factors that affect the performance of a heat sink. Heat sink attachment methods and thermal interface materials also affect the die temperature of the integrated circuit. Thermal adhesive or thermal grease improve the heat sink's performance by filling air gaps between the heat sink and the heat spreader on the device. A heat sink is usually made out of copper and/or aluminium. Copper is used because it has many desirable properties for thermally efficient and durable heat exchangers. First and foremost, copper is an excellent conductor of heat. This means that copper's high thermal conductivity allows heat to pass through it quickly. Aluminum is used in applications where weight is a big concern.",
            "A joystick is an input device consisting of a stick that pivots on a base and reports its angle or direction to the device it is controlling. A joystick, also known as the control column, is the principal control device in the cockpit of many civilian and military aircraft, either as a center stick or side-stick. It often has supplementary switches to control various aspects of the aircraft's flight.\n" +
                    "Joysticks are often used to control video games, and usually have one or more push-buttons whose state can also be read by the computer. A popular variation of the joystick used on modern video game consoles is the analog stick. Joysticks are also used for controlling machines such as cranes, trucks, underwater unmanned vehicles, wheelchairs, surveillance cameras, and zero turning radius lawn mowers. Miniature finger-operated joysticks have been adopted as input devices for smaller electronic equipment such as mobile phones.",
            "In computing, a computer keyboard is a typewriter-style device which uses an arrangement of buttons or keys to act as a mechanical lever or electronic switch. Following the decline of punch cards and paper tape, interaction via teleprinter-style keyboards became the main input device for computers.\n" +
                    "A keyboard typically has characters engraved or printed on the keys and each press of a key typically corresponds to a single written symbol. However, to produce some symbols requires pressing and holding several keys simultaneously or in sequence. While most keyboard keys produce letters, numbers or signs (characters), other keys or simultaneous key presses can produce actions or execute computer commands.\n" +
                    "Despite the development of alternative input devices, such as the mouse, touchscreen, pen devices, character recognition and voice recognition, the keyboard remains the most commonly used device for direct (human) input of alphanumeric data into computers.\n" +
                    "In normal usage, the keyboard is used as a text entry interface to type text and numbers into a word processor, text editor or other programs. In a modern computer, the interpretation of key presses is generally left to the software. A computer keyboard distinguishes each physical key from every other and reports all key presses to the controlling software. Keyboards are also used for computer gaming, either with regular keyboards or by using keyboards with special gaming features, which can expedite frequently used keystroke combinations. A keyboard is also used to give commands to the operating system of a computer, such as Windows' Control-Alt-Delete combination, which brings up a task window or shuts down the machine. A command-line interface is a type of user interface operated entirely through a keyboard, or another device doing the job of one.",
            "A liquid-crystal display (LCD) is a flat-panel display or other electronic visual display that uses the light-modulating properties of liquid crystals. Liquid crystals do not emit light directly.LCDs are available to display arbitrary images (as in a general-purpose computer display) or fixed images with low information content, which can be displayed or hidden, such as preset words, digits, and 7-segment displays as in a digital clock. They use the same basic technology, except that arbitrary images are made up of a large number of small pixels, while other displays have larger elements.\n" +
                    "LCDs are used in a wide range of applications including computer monitors, televisions, instrument panels, aircraft cockpit displays, and signage. They are common in consumer devices such as DVD players, gaming devices, clocks, watches, calculators, and telephones, and have replaced cathode ray tube (CRT) displays in nearly all applications. They are available in a wider range of screen sizes than CRT and plasma displays, and since they do not use phosphors, they do not suffer image burn-in. LCDs are, however, susceptible to image persistence.The LCD screen is more energy-efficient and can be disposed of more safely than a CRT can. Its low electrical power consumption enables it to be used in battery-powered electronic equipment more efficiently than CRTs can be. It is an electronically modulated optical device made up of any number of segments controlling a layer of liquid crystals and arrayed in front of a light source (backlight) or reflector to produce images in color or monochrome. Liquid crystals were first discovered in 1888. By 2008, annual sales of televisions with LCD screens exceeded sales of CRT units worldwide, and the CRT became obsolete for most purposes.",
            "In computing, memory refers to the computer hardware devices used to store information for immediate use in a computer; it is synonymous with the term \"primary storage\". Computer memory operates at a high speed, for example random-access memory (RAM), as a distinction from storage that provides slow-to-access program and data storage but offers higher capacities. If needed, contents of the computer memory can be transferred to secondary storage, through a memory management technique called \"virtual memory\". An archaic synonym for memory is store.The term \"memory\", meaning \"primary storage\" or \"main memory\", is often associated with addressable semiconductor memory, i.e. integrated circuits consisting of silicon-based transistors, used for example as primary storage but also other purposes in computers and other digital electronic devices. There are two main kinds of semiconductor memory, volatile and non-volatile. Examples of non-volatile memory are flash memory (used as secondary memory) and ROM, PROM, EPROM and EEPROM memory (used for storing firmware such as BIOS). Examples of volatile memory are primary storage, which is typically dynamic random-access memory (DRAM), and fast CPU cache memory, which is typically static random-access memory (SRAM) that is fast but energy-consuming, offering lower memory areal density than DRAM.\n" +
                    "Most semiconductor memory is organized into memory cells or bistable flip-flops, each storing one bit (0 or 1). Flash memory organization includes both one bit per memory cell and multiple bits per cell (called MLC, Multiple Level Cell). The memory cells are grouped into words of fixed word length, for example 1, 2, 4, 8, 16, 32, 64 or 128 bit. Each word can be accessed by a binary address of N bit, making it possible to store 2 raised by N words in the memory. This implies that processor registers normally are not considered as memory, since they only store one word and do not include an addressing mechanism.\n" +
                    "Typical secondary storage devices are hard disk drives and solid-state drives.",
            "A microphone, colloquially nicknamed mic or mike (/ˈmaɪk/), is an acoustic-to-electric transducer or sensor that converts sound into an electrical signal. Electromagnetic transducers facilitate the conversion of acoustic signals into electrical signals. Microphones are used in many applications such as telephones, hearing aids, public address systems for concert halls and public events, motion picture production, live and recorded audio engineering, two-way radios, megaphones, radio and television broadcasting, and in computers for recording voice, speech recognition, VoIP, and for non-acoustic purposes such as ultrasonic checking or knock sensors.\n" +
                    "Most microphones today use electromagnetic induction (dynamic microphones), capacitance change (condenser microphones) or piezoelectricity (piezoelectric microphones) to produce an electrical signal from air pressure variations. Microphones typically need to be connected to a preamplifier before the signal can be amplified with an audio power amplifier and a speaker or recorder.",
            "A modem (modulator-demodulator) is a network hardware device that modulates one or more carrier wave signals to encode digital information for transmission and demodulates signals to decode the transmitted information. The goal is to produce a signal that can be transmitted easily and decoded to reproduce the original digital data. Modems can be used with any means of transmitting analog signals, from light emitting diodes to radio. A common type of modem is one that turns the digital data of a computer into modulated electrical signal for transmission over telephone lines and demodulated by another modem at the receiver side to recover the digital data.\n" +
                    "Modems are generally classified by the amount of data they can send in a given unit of time, usually expressed in bits per second (symbol bit/s, sometimes abbreviated \"bps\"), or bytes per second (symbol B/s). Modems can also be classified by their symbol rate, measured in baud. The baud unit denotes symbols per second, or the number of times per second the modem sends a new signal. For example, the ITU V.21 standard used audio frequency shift keying with two possible frequencies, corresponding to two distinct symbols (or one bit per symbol), to carry 300 bits per second using 300 baud. By contrast, the original ITU V.22 standard, which could transmit and receive four distinct symbols (two bits per symbol), transmitted 1,200 bits by sending 600 symbols per second (600 baud) using phase shift keying.",
            "A computer monitor or a computer display is an electronic visual display for computers. A monitor usually comprises the display device, circuitry, casing, and power supply. The display device in modern monitors is typically a thin film transistor liquid crystal display (TFT-LCD) or a flat panel LED display, while older monitors used a cathode ray tubes (CRT). It can be connected to the computer via VGA, DVI, HDMI, DisplayPort, Thunderbolt, LVDS (Low-voltage differential signaling) or other proprietary connectors and signals.\n" +
                    "Originally, computer monitors were used for data processing while television receivers were used for entertainment. From the 1980s onwards, computers (and their monitors) have been used for both data processing and entertainment, while televisions have implemented some computer functionality. The common aspect ratio of televisions, and computer monitors, has changed from 4:3 to 16:10, to 16:9.",
            "A motherboard (sometimes alternatively known as the mainboard, system board, baseboard, planar board or logic board, or colloquially, a mobo) is the main printed circuit board (PCB) found in general purpose microcomputers and other expandable systems. It holds and allows communication between many of the crucial electronic components of a system, such as the central processing unit (CPU) and memory, and provides connectors for other peripherals. Unlike a backplane, a motherboard usually contains significant sub-systems such as the central processor, the chipset's input/output and memory controllers, interface connectors, and other components integrated for general purpose use.\n" +
                    "Motherboard specifically refers to a PCB with expansion capability and as the name suggests, this board is often referred to as the \"mother\" of all components attached to it, which often include peripherals, interface cards, and daughtercards: sound cards, video cards, network cards, hard drives, or other forms of persistent storage; TV tuner cards, cards providing extra USB or FireWire slots and a variety of other custom components.\n" +
                    "Similarly, the term mainboard is applied to devices with a single board and no additional expansions or capability, such as controlling boards in laser printers, televisions, washing machines and other embedded systems with limited expansion abilities.",
            "A computer mouse is a pointing device (hand control) that detects two-dimensional motion relative to a surface. This motion is typically translated into the motion of a pointer on a display, which allows a smooth control of the graphical user interface.\n" +
                    "Physically, a mouse consists of an object held in one's hand, with one or more buttons. Mice often also feature other elements, such as touch surfaces and \"wheels\", which enable additional control and dimensional input.",
            "A network interface controller (NIC, also known as a network interface card, network adapter, LAN adapter or physical network interface, and by similar terms) is a computer hardware component that connects a computer to a computer network.Early network interface controllers were commonly implemented on expansion cards that plugged into a computer bus. The low cost and ubiquity of the Ethernet standard means that most newer computers have a network interface built into the motherboard.\n" +
                    "Modern network interface controllers offer advanced features such as interrupt and DMA interfaces to the host processors, support for multiple receive and transmit queues, partitioning into multiple logical interfaces, and on-controller network traffic processing such as the TCP offload engine.",
            "A parallel port is a type of interface found on computers (personal and otherwise) for connecting peripherals. In computing, a parallel port is a parallel communication physical interface. It is also known as a printer port or Centronics port. It was an industry de facto standard for many years, and was finally standardized as IEEE 1284 in the late 1990s, which defined the Enhanced Parallel Port (EPP) and Extended Capability Port (ECP) bi-directional versions. Today, the parallel port interface is virtually non-existent because of the rise of Universal Serial Bus (USB) devices, along with network printing using Ethernet and Wi-Fi connected printers.\n" +
                    "The parallel port interface was originally known as the Parallel Printer Adapter on IBM PC-compatible computers. It was primarily designed to operate printers that used IBM's 8-bit extended ASCII character set to print text, but could also be used to adapt other peripherals. Graphical printers, along with a host of other devices, have been designed to communicate with the system.",
            "A power supply unit (PSU) converts mains AC to low-voltage regulated DC power for the internal components of a computer. Modern personal computers universally use switched-mode power supplies. Some power supplies have a manual switch for selecting input voltage, while others automatically adapt to the mains voltage.\n" +
                    "Most modern desktop personal computer power supplies conform to the ATX specification, which includes form factor and voltage tolerances. While an ATX power supply is connected to the mains supply, it always provides a 5 V standby (5VSB) voltage so that the standby functions on the computer and certain peripherals are powered. ATX power supplies are turned on and off by a signal from the motherboard. They also provide a signal to the motherboard to indicate when the DC voltages are in spec, so that the computer is able to safely power up and boot. The most recent ATX PSU standard is version 2.31 of mid-2008.",
            "In computing, a printer is a peripheral which makes a persistent human readable representation of graphics or text on paper or similar physical media. The two most common printer mechanisms are black and white laser printers used for common documents, and color inkjet printers which can produce high quality photograph output.\n" +
                    "The world's first computer printer was a 19th-century mechanically driven apparatus invented by Charles Babbage for his difference engine. This system used a series of metal rods with characters printed on them and stuck a roll of paper against the rods to print the characters. The first commercial printers generally used mechanisms from electric typewriters and Teletype machines, which operated in a similar fashion. The demand for higher speed led to the development of new systems specifically for computer use. Among the systems widely used through the 1980s were daisy wheel systems similar to typewriters, line printers that produced similar output but at much higher speed, and dot matrix systems that could mix text and graphics but produced relatively low-quality output. The plotter was used for those requiring high quality line art like blueprints.\n" +
                    "The introduction of the low-cost laser printer in 1984 with the first HP LaserJet, and the addition of PostScript in next year's Apple LaserWriter, set off a revolution in printing known as desktop publishing. Laser printers using PostScript mixed text and graphics, like dot-matrix printers, but at quality levels formerly available only from commercial typesetting systems. By 1990, most simple printing tasks like fliers and brochures were now created on personal computers and then laser printed; expensive offset printing systems were being dumped as scrap. The HP Deskjet of 1988 offered the same advantages as laser printer in terms of flexibility, but produced somewhat lower quality output (depending on the paper) from much less expensive mechanisms. Inkjet systems rapidly displaced dot matrix and daisy wheel printers from the market. By the 2000s high-quality printers of this sort had fallen under the $100 price point and became commonplace.\n" +
                    "The rapid update of internet email through the 1990s and into the 2000s has largely displaced the need for printing as a means of moving documents, and a wide variety of reliable storage systems means that a \"physical backup\" is of little benefit today. Even the desire for printed output for \"offline reading\" while on mass transit or aircraft has been displaced by e-book readers and tablet computers. Today, traditional printers are being used more for special purposes, like printing photographs or artwork, and are no longer a must-have peripheral.\n" +
                    "Starting around 2010, 3D printing became an area of intense interest, allowing the creation of physical objects with the same sort of effort as an early laser printer required to produce a brochure. These devices are in their earliest stages of development and have not yet become commonplace.",
            "In computing, a processor is an electronic circuit which performs operations on some external data source, usually memory or some other data stream. The term is frequently used to refer to the Central processing unit in a system, but typical computer systems (especially SoCs) combine a number of specialised \"processors\".",
            "The PS/2 connector is a 6-pin mini-DIN connector used for connecting some keyboards and mice to a PC compatible computer system. Its name comes from the IBM Personal System/2 series of personal computers, with which it was introduced in 1987. The PS/2 mouse connector generally replaced the older DE-9 RS-232 \"serial mouse\" connector, while the PS/2 keyboard connector replaced the larger 5-pin/180° DIN connector used in the IBM PC/AT design. The PS/2 designs on keyboard and mouse interfaces are electrically similar and employ the same communication protocol. However, a given system's keyboard and mouse port may not be interchangeable since the two devices use a different set of commands.",
            "RAID (originally redundant array of inexpensive disks, now commonly redundant array of independent disks) is a data storage virtualization technology that combines multiple physical disk drive components into a single logical unit for the purposes of data redundancy, performance improvement, or both.Data is distributed across the drives in one of several ways, referred to as RAID levels, depending on the required level of redundancy and performance. The different schemas, or data distribution layouts, are named by the word RAID followed by a number, for example RAID 0 or RAID 1. Each schema, or a RAID level, provides a different balance among the key goals: reliability, availability, performance, and capacity. RAID levels greater than RAID 0 provide protection against unrecoverable sector read errors, as well as against failures of whole physical drives.",
            "Random-access memory  is a form of computer data storage. A random-access memory device allows data items to be accessed (read or written) in almost the same amount of time irrespective of the physical location of data inside the memory. In contrast, with other direct-access data storage media such as hard disks, CD-RWs, DVD-RWs and the older drum memory, the time required to read and write data items varies significantly depending on their physical locations on the recording medium, due to mechanical limitations such as media rotation speeds and arm movement.\n" +
                    "RAM contains multiplexing and demultiplexing circuitry, to connect the data lines to the addressed storage for reading or writing the entry. Usually more than one bit of storage is accessed by the same address, and RAM devices often have multiple data lines and are said to be '8-bit' or '16-bit' etc. devices.\n" +
                    "In today's technology, random-access memory takes the form of integrated circuits. RAM is normally associated with volatile types of memory (such as DRAM memory modules), where stored information is lost if power is removed, although many efforts have been made to develop non-volatile RAM chips. Other types of non-volatile memories exist that allow random access for read operations, but either do not allow write operations or have other kinds of limitations on them. These include most types of ROM and a type of flash memory called NOR-Flash.\n" +
                    "Integrated-circuit RAM chips came into the market in the early 1970s, with the first commercially available DRAM chip, the Intel 1103, introduced in October 1970.",
            "A riser card is a printed circuit board that picks up a multitude of signal lines (often bused) via a single connector (usually an edge connector) on a mainboard and distributes them via dedicated connectors on the card.\n" +
                    "Riser cards are often used to allow adding expansion cards to a system enclosed in a low-profile case where the height of the case doesn't allow for a perpendicular placement of the full-height expansion card.\n" +
                    "A riser card is a board that plugs into the system board and provides additional slots for adapter cards. Because it rises above the system board, it enables you to connect additional adapters to the system in an orientation that is parallel to the system board and save space within the system case.",
            "Small Computer System Interface (SCSI) is a set of standards for physically connecting and transferring data between computers and peripheral devices. The SCSI standards define commands, protocols, electrical and optical interfaces. SCSI is most commonly used for hard disk drives and tape drives, but it can connect a wide range of other devices, including scanners and CD drives, although not all controllers can handle all devices. The SCSI standard defines command sets for specific peripheral device types; the presence of \"unknown\" as one of these types means that in theory it can be used as an interface to almost any device, but the standard is highly pragmatic and addressed toward commercial requirements.",
            "In computing, a serial port is a serial communication interface through which information transfers in or out one bit at a time (in contrast to a parallel port). Throughout most of the history of personal computers, data was transferred through serial ports to devices such as modems, terminals and various peripherals.\n" +
                    "While such interfaces as Ethernet, FireWire, and USB all send data as a serial stream, the term \"serial port\" usually identifies hardware more or less compliant to the RS-232 standard, intended to interface with a modem or with a similar communication device.\n" +
                    "Modern computers without serial ports may require serial-to-USB converters to allow compatibility with RS 232 serial devices. Serial ports are still used in applications such as industrial automation systems, scientific instruments, point of sale systems and some industrial and consumer products. Server computers may use a serial port as a control console for diagnostics. Network equipment (such as routers and switches) often use serial console for configuration. Serial ports are still used in these areas as they are simple, cheap and their console functions are highly standardized and widespread. A serial port requires very little supporting software from the host system.",
            "A sound card (also known as an audio card) is an internal computer expansion card that facilitates economical input and output of audio signals to and from a computer under control of computer programs. The term sound card is also applied to external audio interfaces that use software to generate sound, as opposed to using hardware inside the PC. Typical uses of sound cards include providing the audio component for multimedia applications such as music composition, editing video or audio, presentation, education and entertainment (games) and video projection.\n" +
                    "Sound functionality can also be integrated onto the motherboard, using components similar to plug-in cards. The best plug-in cards, which use better and more expensive components, can achieve higher quality than integrated sound. The integrated sound system is often still referred to as a \"sound card\". Sound processing hardware is also present on modern video cards with HDMI to output sound along with the video using that connector; previously they used a SPDIF connection to the motherboard or sound card.",
            "Computer speakers, or multimedia speakers, are speakers sold for use with computers, although usually capable of other audio uses, e.g. for an MP3 player. Most such speakers have an internal amplifier, and consequently require a power source, which may be by a mains power supply often via an AC adapter, batteries, or a USB port (able to supply no more than 2.5W DC, 500mA at 5V). The signal input connector is often a 3.5 mm jack plug (usually color-coded lime green per the PC 99 standard); RCA connectors are sometimes used, and a USB port may supply both signal and power (requiring additional circuitry, and only suitable for use with a computer). Battery-powered wireless Bluetooth speakers require no connections at all. Most computers have speakers of low power and quality built in; when external speakers are connected they disable the built-in speakers. Altec Lansing claims to have created the computer speaker market in 1990.Computer speakers range widely in quality and in price. Computer speakers sometimes packaged with computer systems are small, plastic, and have mediocre sound quality. Some computer speakers have equalization features such as bass and treble controls.\n" +
                    "More sophisticated computer speakers can have a subwoofer unit, to enhance bass output. The larger subwoofer enclosure usually contains the amplifiers for the subwoofer and the left and right speakers.\n" +
                    "Some computer displays have rather basic speakers built-in. Laptop computers have built-in integrated speakers, usually small and of restricted sound quality to conserve space.\n" +
                    "Instead of using a computer speaker for better sound, a computer can be connected to any external sound system, typically a high-power high-quality setup.\n" +
                    "An unusual design by HiWave Technologies, the DyadUSB USB-powered stereo audio amplifier module used in the SoundScience QSB 30W Portable USB Speakers allows a USB-powered and driven stereo speaker pair to supply 30W of power for short periods with a signal that has short high-power peaks and much lower average power, as most music and speech does. It stores energy from the USB connection during quieter periods, delivering high power for the peaks. (With a constant sine-wave input, power output cannot exceed the 2.5W that any USB speaker can deliver). The module is claimed to require less power most of the time, increasing laptop computer battery endurance, and delivering clean, unclipped sound peaks.",
            "Standby power, also called vampire power, vampire draw, phantom load, or leaking electricity (\"phantom load\" and \"leaking electricity\" are defined technical terms with other meanings, adopted for this different purpose), refers to the electric power consumed by electronic and electrical appliances while they are switched off (but are designed to draw some power) or in a standby mode. This only occurs because some devices claimed to be \"switched off\" on the electronic interface, but are in a different state from switching off at the plug, or disconnecting from the power point, which can solve the problem of standby power completely. In fact, switching off at the power point is effective enough, there is no need to disconnect all devices from the power point. Some such devices offer remote controls and digital clock features to the user, while other devices, such as power adapters for disconnected electronic devices, consume power without offering any features (sometimes called no-load power). All of the above examples, such as the remote control, digital clock functions and—in the case of adapters, no-load power—are switched off just by switching off at the power point. However, for some devices with built-in internal battery, such as a phone, the standby functions can be stopped by removing the battery instead.\n" +
                    "In the past, standby power was largely a non-issue for users, electricity providers, manufacturers, and government regulators. In the first decade of the twenty-first century, awareness of the issue grew and it became an important consideration for all parties. Up to the middle of the decade, standby power was often several watts or even tens of watts per appliance. By 2010, regulations were in place in most developed countries restricting standby power of devices sold to one watt (and half that from 2013).",
            "A surge protector (or surge suppressor or surge diverter) is an appliance or device designed to protect electrical devices from voltage spikes. A surge protector attempts to limit the voltage supplied to an electric device by either blocking or shorting to ground any unwanted voltages above a safe threshold. This article primarily discusses specifications and components relevant to the type of protector that diverts (shorts) a voltage spike to ground; however, there is some coverage of other methods.",
            "An uninterruptible power supply, also uninterruptible power source, UPS or battery/flywheel backup, is an electrical apparatus that provides emergency power to a load when the input power source or mains power fails. A UPS differs from an auxiliary or emergency power system or standby generator in that it will provide near-instantaneous protection from input power interruptions, by supplying energy stored in batteries, supercapacitors, or flywheels. The on-battery runtime of most uninterruptible power sources is relatively short (only a few minutes) but sufficient to start a standby power source or properly shut down the protected equipment.\n" +
                    "A UPS is typically used to protect hardware such as computers, data centers, telecommunication equipment or other electrical equipment where an unexpected power disruption could cause injuries, fatalities, serious business disruption or data loss. UPS units range in size from units designed to protect a single computer without a video monitor (around 200 volt-ampere rating) to large units powering entire data centers or buildings. The world's largest UPS, the 46-megawatt Battery Electric Storage System (BESS), in Fairbanks, Alaska, powers the entire city and nearby rural communities during outages.",
            "A video card (also called a video graphics adapter or VGA, display card, graphics card, graphics board, display adapter, graphics adapter GPU or frame buffer) is an expansion card which generates a feed of output images to a display (such as a computer monitor). Frequently, these are advertised as discrete or dedicated graphics cards, emphasizing the distinction between these and integrated graphics. Within the industry, video cards are sometimes called graphics add-in-boards, abbreviated as AIBs, with the word \"graphics\" usually omitted.",
            "The Zip drive is a medium-to-high-capacity (at the time of its release) removable floppy disk storage system that was introduced by Iomega in late 1994. Originally, Zip disks launched with capacities of 100 MB, but later versions increased this to first 250 MB and then 750 MB.\n" +
                    "The format became the most popular of the superfloppy products which filled a niche in the late 1990s portable storage market. However, it was never popular enough to replace the 3.5-inch floppy disk. Later versions of the disc matched the capacity available on rewritable CDs but this was far surpassed by the later rewritable DVDs. USB flash drives ultimately proved to be the better rewritable storage medium among the general public due to the near-ubiquity of USB ports on personal computers and soon after because of the far greater storage sizes offered. Zip drives fell out of favor for mass portable storage during the early 2000s. The Zip brand later covered internal and external CD writers known as Zip-650 or Zip-CD, which had no relation to the Zip drive."

    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_hardware_scrolling);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

       int position =  getIntent().getExtras().getInt("Position");
       setTitle(HardwareList[position]);


        ImageView imageView = (ImageView) findViewById(R.id.imageView);
        String mDrawableName = "hardware_" + position;
        if(getResources().getIdentifier(mDrawableName, "drawable", getPackageName())== 0) {
            mDrawableName = "hardware";
        }

        int resId = getResources().getIdentifier(mDrawableName, "drawable", getPackageName());
        imageView.setImageResource(resId);



        TextView textView = (TextView) findViewById(R.id.context_text);
        assert textView != null;
        textView.setText(HardwareDetails[position]);
        if(getResources().getIdentifier(mDrawableName, "drawable", getPackageName())== 0) {
            TextView newText = (TextView) findViewById(R.id.context_text);
            assert newText != null;
            textView.setText("Crap");
        }



    }
}
